### ISSUE TITLE
Use of uninitialized variable

### ISSUE THREAD

**Issue by andrewchambers** [llmII/jsys#2]
```
src/csys.c:748:23: note: initialize the variable 'name' to silence this warning
    int id; char *name;
                      ^
                       = NULL
src/csys.c:814:42: warning: variable 'name' is uninitialized when used here [-Wuninitialized]
    switch(sys_name_opt(argc, argv, &id, name)) {
```

The sys_name_opt function seems quite broken, I guess you meant char **

**Comment by llmII** [comment]
Correct, that was extremely broken and in no way used like it probably was thought out to be used. A fix will be done soon. This impacted `get*nam` functions, which didn't work at all, and were still not working till using `janet_ckeywordv` instead of `janet_wrap_keyword`. Locally, `getpwnam` works, and I'll push up the fix either when I've got `getgpnam` working or I figure it's better to have it broken but the other working because I'm taking too long to figure out why it's broken.
